### PR TITLE
Fix the MDCMap issue when Threads off

### PR DESCRIPTION
**Pull request by sswguo**

### CODE REVIEW

**Comment by ruhan1** [comment]
I tested below,
`    @Test
    public void run2() throws Exception
    {
        Thread t = new Thread( () -> {
            MDC.put( "A", "A" );
            Thread t2 = new Thread( () -> {
                MDC.put( "B", "B" );
                System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "A" ));
                System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "B" ));
            } );
            t2.start();
            try
            {
                t2.join();
            }
            catch ( Exception e ) {
            }
            System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "B" ));
        } );
        t.start();
        t.join();
    }
`
The output is:
Thread-3 >>> A
Thread-3 >>> B
Thread-2 >>> null
It seems children thread can see parent mdc. But parent thread can not see children's mdc.
If this is true, we just remove all our code related to "mdcMap".

**Comment by sswguo** [comment]
> I try to remove the whole if and the test still passes. This is confusing. Can you try that?

Just tried, looks so. If that, i think it's OK to remove the "if block" .

**Comment by sswguo** [comment]
> I tested below,
> ` @Test public void run2() throws Exception { Thread t = new Thread( () -> { MDC.put( "A", "A" ); Thread t2 = new Thread( () -> { MDC.put( "B", "B" ); System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "A" )); System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "B" )); } ); t2.start(); try { t2.join(); } catch ( Exception e ) { } System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "B" )); } ); t.start(); t.join(); }`
> The output is:
> Thread-3 >>> A
> Thread-3 >>> B
> Thread-2 >>> null
> It seems children thread can see parent mdc. But parent thread can not see children's mdc.
> If this is true, we just remove all our code related to "mdcMap".



> I tested below,
> ` @Test public void run2() throws Exception { Thread t = new Thread( () -> { MDC.put( "A", "A" ); Thread t2 = new Thread( () -> { MDC.put( "B", "B" ); System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "A" )); System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "B" )); } ); t2.start(); try { t2.join(); } catch ( Exception e ) { } System.out.println(Thread.currentThread().getName() + " >>> " + MDC.get( "B" )); } ); t.start(); t.join(); }`
> The output is:
> Thread-3 >>> A
> Thread-3 >>> B
> Thread-2 >>> null
> It seems children thread can see parent mdc. But parent thread can not see children's mdc.
> If this is true, we just remove all our code related to "mdcMap".

I tried it in a standalone application, looks it works for logback 1.0.12, that Weft test ref as default. 
But does not work for logback 1.2.3, that Indy ref.

Still need to investigate further.

**Comment by ruhan1** [comment]
I tried another version. It works until 1.1.4 and fails from 1.1.5. How an ugly regression. :(

**Comment by sswguo** [comment]
That's not a regression as the release note mentioned in version 1.1.5. 
https://logback.qos.ch/news.html
`MDC values are no longer inherited by child threads.`

**Comment by ruhan1** [comment]
MDC auto inheritance might have problems and does not help the thread pool threads. Your fix looks fix a hole where the MDC might have leaked. It looks good.

**Comment by sswguo** [comment]
Yeah, John had considered it at beginning, i just adjusted the copyMDCMap line to make sure that it's been latest. :)

**Pull request merged**
